spring.application.name=InlamningsUppgift

spring.datasource.url=jdbc:mysql://localhost:3306/UthyrningAPI
spring.datasource.username=root
spring.datasource.password=rootpassword

# SWAGGER CONFIGURATION
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.operations-sorter=method
springdoc.swagger-ui.tags-sorter=alpha
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true

spring.jpa.hibernate.ddl-auto=update
spring.jpa.hibernate.dialect=org.hibernate.dialect.MySQLDialect

